# Site settings
title: Juho Heikkinen - Azure Developer / Programmer
email: contact.juhoheikkinen@gmail.com
description: > # keep this and put description below
  Azure Developer, programmer, 3D-modeler, game developer, pixel- and lowpoly-art lover.
url: "https://crare.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/juhopmheikkinen/"
github_username: crare
twitter_username: jukepoks1
itchio_username: jukepoks1
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
